### ISSUE TITLE
Fantastic Demo!  However, everything went well until the compile step.

### ISSUE THREAD

**Issue by MattBeasley** [uberfire/uberfire-tutorial#1]
I get this error when I do 'mvn compile'
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.4:compile (default-compile) on project WorkflowApp: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:2.4:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:2.4 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.uberfire:uberfire-workbench-processors:jar:0.5.0-SNAPSHOT, org.uberfire:uberfire-client-api:jar:0.5.0-SNAPSHOT, org.uberfire:uberfire-security-api:jar:0.5.0-SNAPSHOT: Could not find artifact org.uberfire:uberfire-workbench-processors:jar:0.5.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
[ERROR]

The dependency org.uberfire:uberfire-workbench-processors:jar:0.5.0-SNAPSHOT is in my .m2/repository.  It was downloaded at the beginning of the compile process.  But, when the maven-compiler-plugin kicks in, I get the above error message.  I've even downloaded the repository from git and the same thing happens.  I have http://repository.jboss.org/nexus/content/repositories/snapshots/ in my .m2/settings.xml file.   And, like I said, I can see the jar file was downloaded.  Thoughts?

**Comment by ederign** [comment]
Hi @MattBeasley, we have made a huge improvement on docs and tutorial. This should solve your issues!
